# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET Beta

on:
  push:
    branches: 
      - '*'
      - '!Trunk'
      - '!Development'
      
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: increment version
      uses: action-pack/increment@v2
      with:
        name: 'BETA_PACKAGE_VERSION'
        token: ${{ secrets.NUGET_PACKAGE_TOKEN }}

    - name: Version Number
      run: echo "1.0.${{ vars.PACKAGE_VERSION }}-beta${{ vars.BETA_PACKAGE_VERSION }}"
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Debug
      
    - name: Pack
      run: dotnet pack --no-build --configuration Debug -p:PackageVersion="1.0.${{ vars.PACKAGE_VERSION }}-beta${{ vars.BETA_PACKAGE_VERSION }}"

    - name: Publish the package to GPR
      run: dotnet nuget push "Libs/*/bin/Debug/*1.0.${{ vars.PACKAGE_VERSION }}-alpha${{ vars.DEV_PACKAGE_VERSION }}.nupkg"  --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }} --source "github" --skip-duplicate
