# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
env:
  PACKAGE_VERSION: 24

name: .NET Release

on:
  push:
    branches: 
      - "Trunk"
      
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Regex Replace
      uses: ashley-taylor/regex-property-action@v1.4
      with:
        # The text of the regex pattern
        regex: "<Version>(?'version'[0-9.]+)<\/Version>"
        # String that replaces the substring specified by the regex
        replacement: "<Version>1.0.$PACKAGE_VERSION</Version>"
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Pack
      run: dotnet pack --no-restore --configuration Release

    - name: Publish the package to GPR
      run: dotnet nuget push "Libs/*/bin/Release/*.nupkg"  --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }} --source "github" --skip-duplicate
